CI pipeline implemented

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -5,8 +5,15 @@ name: CI/CD Pipeline
 on:
   push:
     branches: ["*"]
+    paths-ignore:
+      - 'kubernetes/**'
   pull_request:
     branches: ["*"]
+
+env:
+  DOCKER_REGISTRY: ghcr.io
+  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/jerney-backend
+  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/jerney-frontend
 
 jobs:
 # ==============================================================
@@ -72,6 +79,7 @@ jobs:
 # STAGE 3: Build and Push - Docker Images on GitHub Container Registry 
 # ==============================================================
   build:
+    if: github.actor != 'github-actions[bot]'
     name: "Build ${{ matrix.component }}"
     runs-on: ubuntu-latest
     needs: sca
@@ -154,7 +162,95 @@ jobs:
 #   # STAGE 5: IaC Security Scan (Checkov) — Terraform + K8s
 #   # ==============================================================
 
+  iac-scan:
+    name: IAC Security Scan
+    runs-on: ubuntu-latest
+    needs: lint
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v7
+    
+    - name: Scanning Terraform using Checkov
+      uses: bridgecrewio/checkov-action@master
+      with:
+        directory: terraform
+        framework: terraform
+        soft_fail: false
+        skip_check: CKV_AWS_39,CKV_AWS_58  # Public EKS endpoint (intentional for dev)
+        output_format: cli
+      
+    - name: Scanning Kubernetes using Checkov 
+      uses: bridgecrewio/checkov-action@master
+      with:
+        directory: kubernetes
+        framework: kubernetes
+        soft_fail: true # Soft fail for K8s (some checks may not apply)
+        output_format: cli
 
+
+#   # ==============================================================
+#   # STAGE 6: Dockerfile Scan - Hadolint - Syntax linting and strict Dockerfile best practices
+#   # ==============================================================
+
+  dockerfile-lint:
+    name: Scan Dockerfile using Hadolint 
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        component: [backend, frontend]
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v7
+    
+    - name: Scanning ${{ matrix.component }} Dockerfile
+      uses: hadolint/hadolint-action@v3.1.0
+      with:
+        dockerfile: ${{ matrix.component }}/Dockerfile
+        failure-threshold: warning
+
+
+#   # ==============================================================
+#   # STAGE 7: Update K8s Manifest with New Image Tag
+#   # Only runs on push to main (not on PRs)
+#   # ==============================================================
+
+  update-manifest:
+    if: github.actor != 'github-actions[bot]'
+    name: Update Image tag on k8 manifest on each build
+    runs-on: ubuntu-latest
+    needs: [build, image-scan, iac-scan, dockerfile-lint] 
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v7
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+    
+    - name: Get short SHA
+      id: sha
+      run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT"
+
+    - name: Update K8 manifest with new image tags
+      run: |
+        IMAGE_TAG=${{ steps.sha.outputs.short }}
+
+        # Update backend image
+        sed -i "s|image: .*jerney-backend.*|image: ${BACKEND_IMAGE}:${IMAGE_TAG}|g" kubernetes/05-backend-deployment.yml
+
+        # Update frontend image
+        sed -i "s|image: .*jerney-frontend.*|image: ${FRONTEND_IMAGE}:${IMAGE_TAG}|g" kubernetes/04-frontend-deployment.yml
+
+        echo "✅ Updated images to tag: ${IMAGE_TAG}"
+
+    - name: Commit and Push updated manifest
+      run: |
+        git config --global user.name "Github Actions"
+        git config --global user.email "actions@github"
+
+        git add kubernetes/*
+        git commit -m "Updated Kubernetes manifests with new image tags for commit ${{ steps.sha.outputs.short }}" || echo "No changes to commit"
+        git push origin himanshu
 
 
 
@@ -183,5 +279,63 @@ jobs:
 # Compliance
 # Security audits
 
+#Checkov
+#Checkov is a tool used to scan Infrastructure as Code (IaC), container images, and open-source packages for security and compliance misconfigurations.
+
+# soft_fail : it controls Checkov breaks your CI pipeline when it finds issues. If true it wont break, if false then there will be strict scanning.
+
+# soft_fail: false
+
+# 👉 If ANY policy fails:
+
+# ❌ Step fails
+# ❌ Pipeline fails
+# ❌ Deployment blocked
+
+# ✔️ Use this for:
+
+# Terraform (in your case)
+# Production environments
+# Security-critical infra
 
 
+# soft_fail: true
+
+# 👉 If issues are found:
+
+# ⚠️ Issues are shown
+# ✅ Pipeline CONTINUES
+
+# ✔️ Use this for:
+
+# Kubernetes manifests (like you did)
+# Early-stage projects
+# When some checks are not applicable
+
+
+
+# skip_check -> Tells Checkov: “Don’t flag these specific security checks” 
+# skip_check: CKV_AWS_39,CKV_AWS_58
+
+# You are skipping:
+# CKV_AWS_39 → EKS public endpoint
+# CKV_AWS_58 → Another AWS-related security rule
+
+# Skipping = you accept the risk
+
+# CKV_AWS_39 -> It’s a policy ID defined by Checkov. Checkov has a huge built-in library of security rules, and each rule gets a unique ID like:
+# CKV_<PROVIDER>_<NUMBER>
+
+
+# output_format — How results are displayed
+
+# ✅ What it does
+
+# Controls how scan results are formatted.
+
+# Common options:
+# Format	Description
+# cli	Human-readable terminal output
+# json	Machine-readable (for tools, dashboards)
+# sarif	GitHub Security tab integration
+# junitxml	CI test reporting
